# -*- coding: utf-8 -*-

"""
/***************************************************************************
Isochrone_GIS_processing
                                 A QGIS plugin
 Outil de calcul de temps de trajets multimodaux
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-11
        copyright            : (C) 2024 by C.Garcia - JL.Humbert from Inddigo
        email                : c.garcia@inddigo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'C.Garcia - JL.Humbert from Inddigo'
__date__ = '2024-10-11'
__copyright__ = '(C) 2024 by C.Garcia - JL.Humbert from Inddigo'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
from qgis.PyQt.QtWidgets import QMessageBox

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterDateTime,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsWkbTypes, 
                       QgsField, 
                       QgsFeature,
                       QgsProcessingException,
                       QgsFields,
                       QgsExpressionContextUtils
                       )
from PyQt5.QtCore import QVariant
from .modules.get_pieton import tppietonhere
from .modules.get_bike import tpgvelohere
from .modules.get_car import tpcarhere
from .modules.get_car_trafic import tpcartrafichere
from .modules.get_tc import tptchere

from .utils.utils import sanitize_value, safe_string, saveInDb


# Herekey = None
# # Replace 'variable_name' with the name of your global variable
# variable_name = 'hereapikey'

# # Get the global variable value
# try : 
#     Herekey = QgsExpressionContextUtils.globalScope().variable(variable_name)
# except Exception as e: 
#     print(e)

class isochrone(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT1 = 'INPUT1'
    ID_FIELD1_JOIN = 'ID_FIELD1_JOIN'
    DATE_FIELD = 'DATE_FIELD'
    CKB_DEPART_OU_ARRIVEE = 'CKB_DEPART_OU_ARRIVEE'
    CHECKBOXES_MODES = 'CHECKBOXES_MODES'
    DIST_MAX_MARCHE = 'DIST_MAX_MARCHE'
    VALEUR_MAX = 'VALEUR_MAX'
    VALEUR_INTERMEDIAIRES = 'VALEUR_INTERMEDIAIRES'


    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT1,
                self.tr('Input layer 1 '),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Resultat_isochrone')
            )
        )

        # Menu déroulant pour le champ id origine servant à la jointure
        self.addParameter(
            QgsProcessingParameterField(
                self.ID_FIELD1_JOIN,
                self.tr('Champ ID de la couche 1'),
                '',
                parentLayerParameterName=self.INPUT1,  # Lie le champ à la couche d'entrée
                type=QgsProcessingParameterField.Numeric  # Limite la sélection aux champs numériques
            )
        )

                # Ajout d'un paramètre de calendrier
        self.addParameter(
            QgsProcessingParameterDateTime(
                self.DATE_FIELD,
                self.tr('Selectionner une date'),
                defaultValue=None,  # Vous pouvez définir une valeur par défaut
                optional=False  # Permet de rendre le paramètre facultatif
            )
        )

        # Paramètre pour une liste de valeurs texte séparées
        self.addParameter(
            QgsProcessingParameterEnum(
                self.CKB_DEPART_OU_ARRIVEE,
                self.tr("Selectionnez si l'heure indiquée est celle de départ ou d'arrivée"),
                options=["Heure de départ", "Heure d'arrivée"],
                allowMultiple=False,  # Ne permet de cocher qu'une seule réponse
                defaultValue= 1    
            )
        )

        # Boutons à cocher simulés avec un Enum à sélection multiple
        self.addParameter(
            QgsProcessingParameterEnum(
                self.CHECKBOXES_MODES,
                self.tr("Selectionnez les modes que vous voulez requêter"),
                options=["Piéton", "Vélo", "Voiture", "Voiture avec trafic", "Transport en commun"],
                allowMultiple=True,  # Permet de cocher plusieurs options
                defaultValue=[0, 1]  # Option 1 et 2 cochées par défaut
            )
        )

        # Paramètre temps de marche maximum
        self.addParameter(
            QgsProcessingParameterString(
                self.DIST_MAX_MARCHE,
                self.tr("Distance max à pied (en mètres)"),
                defaultValue="300"
            )
        )


    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source1 = self.parameterAsSource(parameters, self.INPUT1, context)
        s_id1 = self.parameterAsString(parameters, self.ID_FIELD1_JOIN, context)
        selected_date = self.parameterAsDateTime(parameters, self.DATE_FIELD, context)
        selected_checkboxes = self.parameterAsEnums(parameters, self.CHECKBOXES_MODES, context)
        tps_marche_max = self.parameterAsString(parameters,self.DIST_MAX_MARCHE, context)

        if not source1:
            raise QgsProcessingException("Impossible de charger les couches d'entrée.")

        result = print('hello')
        return result

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Isochrone'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return 'Isochrone'

    def group(self):
        return "Les plugins restreints du pôle DG d\'Inddigo" 

    def groupId(self):
        return 'Les plugins restreints du pôle DG d\'Inddigo'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return isochrone()
